### ISSUE TITLE
Undefined while parsing a demo

### ISSUE THREAD

**Issue by niekcandaele** [BeepIsla/demo-crosshair-code#1]
Looks like a cool tool, got an error while trying to parse a demo though.

![image](https://user-images.githubusercontent.com/22315101/81048384-88e61f80-8ebc-11ea-820c-eba85d2d891d.png)

**Comment by BeepIsla** [comment]
What demo are you trying to parse? Do you have a link to it?

What browser are you using and what version of that browser?

**Comment by niekcandaele** [comment]
Hey, sorry for that crappy report! I see you added a check for old demos which properly fires now :smile: This can be closed I think
