### ISSUE TITLE
suddenly it doesn't work

### ISSUE THREAD

**Issue by solomonqt** [BeepIsla/demo-crosshair-code#2]
Well, it seems to -just not work- any longer. It worked one day, the next day it didn't. Any ideas what happened?

**Comment by BeepIsla** [comment]
What do you mean with "doesn't work"? Does it just show nothing? If you open the console of your browser does it show any errors?

**Comment by solomonqt** [comment]
Well that was fast. I drop the demo in and the loading, spinny thingy just keeps spinning and nothing happens :-)

**Comment by solomonqt** [comment]
I'll check error

Edit:
`Uncaught (in promise) RangeError: Illegal starting byte: 172
    at Object.utfx.decodeUTF8 (lodash.js:4336)
    at Object.utfx.decodeUTF8toUTF16 (lodash.js:4411)
    at ByteBufferPrototype.readUTF8String (lodash.js:2768)
    at parseHeader (demo.js:93)
    at DemoFile.parse (demo.js:197)
    at _FileLoaded (index.js:34)`

**Comment by BeepIsla** [comment]
Can you give me an example demo I can use to test?

**Comment by solomonqt** [comment]
Hmm Okay so I'm not completely sure if this started occuring after I re-installed Windows or before that but I may be such a retard I've tried to upload .rar-files of demos as the Icon when I didn't have WinRar installed, is the same as normal demo-files........
