### ISSUE TITLE
Loading button 

### ISSUE THREAD

**Issue by marinhuana123** [BeepIsla/demo-crosshair-code#3]
Hi, 
Can i get help? 
When i drop demo to site it is just showing loading thing and doing nothing.
Error code: Uncaught (in promise) RangeError: Illegal starting byte: 139
    at Object.utfx.decodeUTF8 (bundle.js:52675:28)
    at Object.utfx.decodeUTF8toUTF16 (bundle.js:52750:20)
    at ByteBufferPrototype.readUTF8String (bundle.js:51107:20)
    at parseHeader (bundle.js:153:16)
    at DemoFile.parse (bundle.js:262:27)
    at _FileLoaded (index.js:34:12)
Btw i am downloading new demos from faceit.
Thanks!

**Comment by BeepIsla** [comment]
Can you provide a link to the demo?

**Comment by marinhuana123** [comment]
https://www.faceit.com/en/csgo/room/1-96bb6da1-656a-417f-bd5d-b0e6dc79ee78
download demo and try, to me it is not working.

**Comment by marinhuana123** [comment]
And it is showing this:
Failed to load resource: the server responded with a status of 404 ()

**Comment by BeepIsla** [comment]
You downloaded a ZIP file (`.gz`), you have to use a program like WinRAR or 7Zip to unzip the file. You will then have a `.dem`, you have to use that file. The website only supports `.dem` files

**Comment by marinhuana123** [comment]
ty a lot man, you can close the issue
