### ISSUE TITLE
CS2 demos

### ISSUE THREAD

**Issue by ztfrz** [BeepIsla/demo-crosshair-code#4]
I've noticed that you can't get crosshair codes from cs2 demos so it would be nice if you could implement it

![image](https://github.com/BeepIsla/demo-crosshair-code/assets/104774090/32e228fb-9e4b-428b-bbb9-c078e3085203)

**Comment by BeepIsla** [comment]
I am not gonna make a library for parsing demos myself so unless I come across one which works on the web this might never happen.

**Comment by tosha7333** [comment]
And for how much money can you write a library?

**Comment by BeepIsla** [comment]
I just saw https://github.com/LaihoE/demoparser/ seems to have added WASM support, meaning it should be able to run in the browser now, I will take a look later and try to upgrade this project to work with CS2.

**Comment by BeepIsla** [comment]
A new version with CS2 support is now live, try it out: https://beepisla.github.io/demo-crosshair-code/

**Comment by tosha7333** [comment]
Thanks! You've made it very easy for me to work for the project [https://cs-config.ru](url)

**Comment by tosha7333** [comment]
Hi, there is a problem with the demo from faicet. I tried to look at the sights from this demo and I got an error - https://www.faceit.com/ru/cs2/room/1-312db296-c881-4580-94a4-debdef3cdd0b/scoreboard

**Comment by BeepIsla** [comment]
Maybe too old? The match is 9 days old. I tested a demo recorded yesterday and it works fine. Valve updates the game a lot and sometimes old things break :/

**Comment by tosha7333** [comment]
Have you tried the demo I sent you? Hmm. I'll try again from another PC

**Comment by BeepIsla** [comment]
The demo you sent does not work. I think its too old. A different computer will not make a difference.

**Comment by tosha7333** [comment]
I decided to try a fresh game from m0NESY, it took place on November 21 at 2:22 AM - https://www.faceit.com/ru/cs2/room/1-80dac4e6-90b8-44c5-b585-5b0e7e6f2f38 - It doesn't work either

Perhaps the following demos will work

**Comment by BeepIsla** [comment]
It works when using NodeJS or Python, I don't know why it doesn't work on the web. I've opened an issue on the demoparser's repository.

**Comment by BeepIsla** [comment]
Should be fixed now.
