### ISSUE TITLE
Can't read FACEIT demos

### ISSUE THREAD

**Issue by DANDEKER** [BeepIsla/demo-crosshair-code#6]
When I insert demo from HLTV.ORG (tournaments etc) its read perfectly
When I insert demo from Faceit its gives error

An error occurred: RuntimeError: unreachable executed

Please select another file or report this issue.

**Comment by BeepIsla** [comment]
Probably one of the recent updates broke it, I'll check it out

**Comment by BeepIsla** [comment]
Should be fixed now, give it a shot.

**Comment by DANDEKER** [comment]
yeah its fixed 

> Should be fixed now, give it a shot.
